language: python
python:
  - 3.4
env:
  - DJANGO_SETTINGS_MODULE=?engraved.settings.base?
install:
  - pip install -r requirements/travis.txt
before_script:
  - python manage.py syncdb -migrate -noinput
script:
  - tox